export const FETCH_GET_PIZZAS_SUCCESS = "FETCH_GET_PIZZAS_SUCCESS";
export const FETCH_GET_PIZZAS_FAILURE = "FETCH_GET_PIZZAS_FAILURE";

export const ADD_NEW_PIZZA_SUCCESS = "ADD_NEW_PIZZA_SUCCESS";
export const ADD_NEW_PIZZA_FAILURE = "ADD_NEW_PIZZA_FAILURE";

export const FETCH_GET_ORDERS_SUCCESS = "FETCH_GET_ORDERS_SUCCESS";
export const FETCH_GET_ORDERS_FAILURE = "FETCH_GET_ORDERS_FAILURE";

export const GET_ID = "GET_ID";
export const SET_TOTAL_ORDERS = "SET_TOTAL_ORDERS";